
anchor_job_defaults: &job_defaults
  working_directory: ~/prettier-config
  docker:
    - image: ptsecurity/node-container:0.0.4

version: 2
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"

  publish:
    <<: *job_defaults
    steps:
      - checkout      
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+(?:\.\d+)*$/
