version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm test
  publish:
    working_directory: ~/prettier-config
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish
  
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+(?:\.\d+)*$/
